.TH lodstack_analyse_packages 1  "02/2014" "version 1.0" "USER COMMANDS"
.SH NAME
lodstack_analyse_packaes \- 
.SH SYNOPSIS
.B lodstack_analyse_packages [options]* 
[option]
.SH DESCRIPTION
For each package found in the "incoming package directory" an attempt
is made to test whether it is installable or not (using piuparts). Then
for each package Lintian is executed to see if there are any obvious 
problems which need to be dealt with. Finally, an attempt is made to 
build from source each of the packages in the appropriate environment.
The environments need to be created beforehand. 
.P
Once the run is completed a report will be constructed in the appropriate 
format (-F html or csv). The csv format is always produced.
.TP
-h               - this message (and the list of options)
.TP
-v               - verbose
.TP
      -i <dir>     - incoming packages directory
.TP
      -l <dir>     : log files directory
.TP
      -p <version> : run piuparts test tool
.TP
      -C           : remove the SRCDIR at the end of the process (save space!)
.TP
      -L           : run lintian tests
.TP
      -F <fmt>     : output can be as HTML or CSV format
.TP
      -B           : source build tests
.TP
      -s           : verify the signatures (default: no)
.TP
      -S           : source directory for getting the DSC/SOURCES (${SRCDIR})
.TP
      -f <file>    : file contains a list of package names
.PP
Will create the binary debian package for installing the <jarfile>.
.PP
The script should be executed via a crontab, with one run as root
and one as a normal user (for the Lintian checks).
.SH EXAMPLE
.TP
	lodstack_analyse_packages -LBF html
.P
which will generate run lintian, build the packages and create 
the resport in html format.
.SH BUGS
.P
Report bugs to <paul.massey@tenforce.com>
.SH AUTHOR
.P
Written by Paul Massey <paul.massey@tenforce.com>
.SH SEE ALSO
.P
piuparts, pbuilder, schroot, lintian
.SS
https://github.com/LinkedDataStack/LinkedDataStackConfigurator/tree/master/SupportPackages/lodstack_analyse_packages
.TP
The main homepage on github



