.TH update_packafes 1  "02/2014" "version 1.0" "USER COMMANDS"
.SH NAME
update_packages \- Recover the latest version of a list of packages
.SH SYNOPSIS
.B update_packages [options]* 
[option]
.SH DESCRIPTION
.P
recover the list of packages
.SH BUGS
.P
Report bugs to <paul.massey@tenforce.com>
.SH AUTHOR
.P
Written by Paul Massey <paul.massey@tenforce.com>
.SH SEE ALSO
.P
piuparts, pbuilder, schroot, lintian, lodstack-analyse-packages
.SH NOTES
.TP
The main homepage on github
https://github.com/LinkedDataStack/LinkedDataStackConfigurator/tree/master/SupportPackages/lodstack_analyse_packages
